### ISSUE TITLE
Render issue on hackage page

### ISSUE THREAD

**Issue by waynee95** [vrom911/slist#19]
Not sure if this is already known, but on the hackage page the rendering of the table is broken. It seems that hackage does not support tables.

I found [this](https://stackoverflow.com/a/41624459) compromise. 

It's not a huge issue, just noticed it.

**Comment by vrom911** [comment]
Yeah, this is a [known Hackage issue](https://github.com/haskell/hackage-server/issues/565). I am still hoping that this would be implemented soon, because the row code block table won't work for quite wide tables, and also it will scroll on some devices, which would make them kinda useless...

**Comment by waynee95** [comment]
I see, thanks for clarifying!

**Comment by vrom911** [comment]
No worries! Thanks for the suggestion, I really appreciate that :+1:
