### ISSUE TITLE
Add `chunksOf`

### ISSUE THREAD

**Issue by chshersh** [vrom911/slist#24]
What do you think about adding the following function?

```haskell
chunksOf :: Int -> Slist a -> Slist (Slist a)
```

For ordinary lists it would work like this:

```haskell
ghci> chunksOf 3 [0..7]
[[0,1,2], [3,4,5], [6,7]]
```

But since we have access to the list length, we can implement a more efficient version of `chunksOf`.

**Comment by vrom911** [comment]
Nice! I like the idea :+1:
