### ISSUE TITLE
[RFC] Integration with `containers`

### ISSUE THREAD

**Issue by chshersh** [vrom911/slist#35]
While using `slist`, I've noticed that sometimes I want to convert `Map/Set` to `slist` more efficiently than using the `slist` function. I'm thinking about adding integration with `containers` and providing functions:

```haskell
mapToVals :: Map k v -> Slist v
mapToKeys :: Map k v -> Slist k
mapToPairs :: Map k v -> Slist (k, v)

setToSlist :: Set a -> Slist a
```

If we depend on `containers`, we also can provide a more efficient versions of some helpful functions:

```haskell
ordNub :: Ord a => Slist a -> Slist a
countUnique :: Ord a => Slist a -> Int  -- number of unique elements
```

**Comment by vrom911** [comment]
Do you think it worth to create a separate package `slist-containers` for that?
I personally feel that this would be a better solution than expanding this package itself, but I can see some downsides too.

**Comment by chshersh** [comment]
@vrom911 I thought about that as well. On the one hand, `containers` is a boot library and adding it to dependency doesn't bring the extra cost in terms of build times. On the other hand, `slist` already provides quite big and useful API and there's some sense in keeping this API under control and depending only on `base`. I imagine there could be a lot of functions to work with `containers` in some future. Maintaining a separate package is more challenging, but most likely also a more proper solution.
