### ISSUE TITLE
Add generic operations

### ISSUE THREAD

**Issue by vrom911** [vrom911/slist#6]
https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List.html#g:26

**Comment by waynee95** [comment]
This is still open right? If so, I would like to work on it.

**Comment by vrom911** [comment]
Yes, thank you, go ahead!

**Comment by waynee95** [comment]
Sorry, that you didn't hear back from me sooner. Had some RL stuff to take care of and getting cabal working, but I got it now!

I already got half of the functions working, but I might have a few questions about one or two functions regarding the implementation, also taking into account the comments on the closed PR for this issue.

**Comment by vrom911** [comment]
No worries, @waynee95 , thanks for working on it!

You could open a draft PR and we can discuss stuff in there, if you prefer :slightly_smiling_face:
